### ISSUE TITLE
wrong launch path

### ISSUE THREAD

**Issue by enganese** [EqualGames/game-scanner#35]
wrong launch path to Fortnite, it shows epicgames launcher instead of FortniteClient-Win64-Shipping.exe

**Comment by matheusalbino** [comment]
Hi,
Thanks for using this project! 

This project tries to provide all commands to interact with the game through the launcher commands.

Interacting with games out of the launcher could cause issues. The launcher could execute some operations for the game works correctly.

For which purpose do you need the path of the game executable? Does this launch command not working?

**Comment by matheusalbino** [comment]
@enganese

This issue has been closed because it has been inactive for 30 days. 
You may reopen this issue if it has been closed in error.
